name: hastrade
version: 1.0.0+1
description: HasTrade - Signal Trading Terpecaya

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  introduction_screen:
  cupertino_icons:
  hexcolor:
  font_awesome_flutter:
  otp_text_field:
  convex_bottom_bar:
  carousel_slider:
  shared_preferences:
  http:
  win32:
  stylish_dialog:
  getwidget:
  flutter_html:
  youtube_player_flutter:
  get:
  image_picker:
  pinput:
  cached_network_image:
  flutter_cache_manager:
  flick_video_player:
  video_player:
  intl:
  url_launcher:

dev_dependencies:
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logoHastrade.png"

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logoHastrade.png
    - assets/textHasTrade.png